<<<<<<< HEAD
# Generated by Django 2.0.7 on 2020-04-09 16:17
=======
# Generated by Django 3.0.3 on 2020-04-09 16:02
>>>>>>> 3291e5623542141157588034829e2f6ba0f012db

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isDelete', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=20, verbose_name='商品分类')),
            ],
            options={
                'verbose_name': '商品分类',
                'verbose_name_plural': '商品分类',
            },
        ),
        migrations.CreateModel(
            name='GoodsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isDelete', models.BooleanField(default=False)),
                ('goods_title', models.CharField(max_length=20, unique=True, verbose_name='商品名称')),
<<<<<<< HEAD
                ('goods_image', models.ImageField(blank=True, null=True, upload_to='df_goods/image/%Y/%m', verbose_name='商品图片')),
=======
>>>>>>> 3291e5623542141157588034829e2f6ba0f012db
                ('goods_price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='商品价格')),
                ('goods_unit', models.CharField(default='230g', max_length=20, verbose_name='单个商品重量')),
                ('goods_click', models.IntegerField(default='0', verbose_name='点击量')),
                ('goods_jianjie', models.CharField(max_length=200, verbose_name='商品简介')),
                ('goods_kucun', models.IntegerField(default=0, verbose_name='商品库存')),
                ('goods_content', models.TextField(verbose_name='商品详情')),
                ('goods_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttl_goods.TypeInfo', verbose_name='商品分类')),
            ],
        ),
<<<<<<< HEAD
        migrations.CreateModel(
            name='TypeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isDelete', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=20, verbose_name='商品分类')),
            ],
            options={
                'verbose_name': '商品分类',
                'verbose_name_plural': '商品分类',
            },
        ),
        migrations.AddField(
            model_name='goodsinfo',
            name='goods_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttl_goods.TypeInfo', verbose_name='商品分类'),
        ),
=======
>>>>>>> 3291e5623542141157588034829e2f6ba0f012db
    ]
