# Generated by Django 3.0.4 on 2020-04-02 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ttl_goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isDelete', models.BooleanField(default=False)),
                ('goods_title', models.CharField(max_length=20, unique=True, verbose_name='商品名称')),
                ('goods_image', models.ImageField(null=True, upload_to='图片路径', verbose_name='商品图片')),
                ('goods_price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='商品价格')),
                ('goods_unit', models.CharField(default='230g', max_length=20, verbose_name='单个商品重量')),
                ('goods_click', models.IntegerField(default='0', verbose_name='点击量')),
                ('goods_jianjie', models.CharField(max_length=200, verbose_name='商品简介')),
                ('goods_kucun', models.IntegerField(default=0, verbose_name='商品库存')),
                ('goods_content', models.TextField(verbose_name='商品详情')),
            ],
        ),
        migrations.CreateModel(
            name='TypeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isDelete', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': '商品分类',
                'verbose_name_plural': '商品分类',
            },
        ),
        migrations.DeleteModel(
            name='Goods',
        ),
        migrations.AddField(
            model_name='goodsinfo',
            name='goods_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttl_goods.TypeInfo', verbose_name='商品分类'),
        ),
    ]
