# Generated by Django 2.0.7 on 2020-04-08 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ttl_goods', '0002_auto_20200401_1650'),
        ('ttl_goods', '0002_auto_20200401_1317'),
        ('ttl_goods', '0002_auto_20200402_1115'),
    ]

    operations = [
    ]
