# Generated by Django 3.0.3 on 2020-04-07 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderNum', models.CharField(max_length=20)),
                ('orderDate', models.DateTimeField()),
                ('orderImage', models.IntegerField()),
                ('orderInfo', models.IntegerField()),
                ('orderUnitPrice', models.IntegerField()),
                ('orderTotalPrice', models.IntegerField()),
                ('orderCount', models.IntegerField()),
                ('orderStatus', models.IntegerField()),
            ],
        ),
    ]
