# Generated by Django 2.0.7 on 2020-04-15 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderNum', models.CharField(max_length=20)),
                ('orderDate', models.CharField(max_length=1000)),
                ('orderImage', models.CharField(max_length=1000)),
                ('orderInfo', models.CharField(max_length=1000)),
                ('orderUnitPrice', models.CharField(max_length=1000)),
                ('orderTotalPrice', models.CharField(max_length=1000)),
                ('orderCount', models.CharField(max_length=1000)),
                ('orderStatus', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('oid', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='大订单号')),
                ('user', models.CharField(max_length=1000)),
                ('odate', models.DateTimeField(auto_now=True, verbose_name='时间')),
                ('oIsPay', models.BooleanField(default=False, verbose_name='是否支付')),
                ('ototal', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='总价')),
                ('oaddress', models.CharField(max_length=150, verbose_name='订单地址')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
            },
        ),
    ]
