# Generated by Django 3.0.3 on 2020-04-07 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttl_order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderNum', models.CharField(max_length=20)),
                ('orderDate', models.CharField(max_length=1000)),
                ('orderImage', models.CharField(max_length=1000)),
                ('orderInfo', models.CharField(max_length=1000)),
                ('orderUnitPrice', models.CharField(max_length=1000)),
                ('orderTotalPrice', models.CharField(max_length=1000)),
                ('orderCount', models.CharField(max_length=1000)),
                ('orderStatus', models.CharField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='Grades',
        ),
    ]
