# Generated by Django 3.0.3 on 2020-04-13 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttl_order', '0002_auto_20200407_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('oid', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='大订单号')),
                ('user', models.CharField(max_length=1000)),
                ('odate', models.DateTimeField(auto_now=True, verbose_name='时间')),
                ('oIsPay', models.BooleanField(default=False, verbose_name='是否支付')),
                ('ototal', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='总价')),
                ('oaddress', models.CharField(max_length=150, verbose_name='订单地址')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
            },
        ),
    ]
