# Generated by Django 3.0.4 on 2020-03-31 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttl_user', '0002_auto_20200331_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='email',
            field=models.EmailField(error_messages={'logo': 'Unique 不可以重复'}, max_length=254, unique=True),
        ),
    ]
