# Generated by Django 3.0.3 on 2020-04-07 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ttl_user', '0003_auto_20200331_1847'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
