# Generated by Django 3.0.3 on 2020-04-04 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttl_user', '0003_auto_20200331_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='password',
            field=models.CharField(max_length=40),
        ),
    ]
