# Generated by Django 3.0.3 on 2020-04-08 17:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ttl_goods', '0001_initial'),
        ('ttl_user', '0004_auto_20200404_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='shou',
            field=models.TextField(default='[]', max_length=5000),
        ),
        migrations.CreateModel(
            name='GoodsBrowser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('browser_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='浏览时间')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttl_goods.GoodsInfo', verbose_name='商品ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttl_user.UserInfo', verbose_name='用户ID')),
            ],
        ),
    ]
