# Generated by Django 3.0.3 on 2020-04-08 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttl_user', '0005_auto_20200408_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='shou',
            field=models.TextField(default='[]', max_length=5000),
        ),
    ]
